version: "3"
services:
  web:
    container_name: appimongodocker
    restart: always
    build: .
    environment:
    - PORT=4000
    - MONGODB_CNN=mongodb://mongo:27017/Inscripcion
    ports:
      - "5000:4000"
    links: 
      - mongo
   
  mongo:
    container_name: mibasemongo
    image: mongo
    ports: 
      - "27017:27017"
