version: '3'

services:

  aspirante:
    build: ./microservices/aspirante-service
    depends_on:
            - mongoasp
    environment:
            - MONGODB_CNN=mongodb://mongoasp:27017/aspirante
  mongoasp: 
    container_name: mongoaspirante
    image: mongo
    ports: 
        - "27017:27017"


  curso:
    build: ./microservices/curso-service
    depends_on:
          - mongocur
    environment:
          - MONGODB_URI=mongodb://mongocur:27017/curso
  mongocur: 
      container_name: mongocurso
      image: mongo
      ports: 
        - "27018:27017"

  nginx:
      image: nginx:latest
      ports:
        - "8081:8081"
      volumes:
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
      depends_on:
        - aspirante
        - curso


    